# Generated by Django 5.1.2 on 2024-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_Tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Medicamento', models.CharField(max_length=50)),
                ('dosis_Administrada', models.FloatField()),
                ('via_Administracion', models.CharField(choices=[('cutanea', 'CUTANEA'), ('inhalada', 'INHALADA'), ('intradermica', 'INTRADERMICA'), ('im_intramuscular', 'IM-INTRAMUSCULAR'), ('iv_intravenosa', 'IV-INTRAVENOSA'), ('nasal', 'NASAL'), ('oftalmica', 'OFTALMICA'), ('oral', 'ORAL'), ('otica', 'OTICA'), ('rectal', 'RECTAL'), ('sonda_nasogastrica', 'SONDA NASOGASTRICA'), ('subcutanea', 'SUBCUTANEA'), ('sublingual', 'SUBLINGUAL'), ('topica', 'TOPICA'), ('vaginal', 'VAGINAL')], max_length=20)),
                ('frecuencia_Dosis', models.DecimalField(decimal_places=0, max_digits=2)),
                ('tiempo_Dosis', models.CharField(choices=[('hrs', 'HRS'), ('mins', 'MINS'), ('unica', 'UNICA'), ('prn', 'PRN')], max_length=10)),
                ('duracion_Terapia', models.DecimalField(decimal_places=0, max_digits=2)),
                ('otras_Indicaciones', models.CharField(max_length=1000)),
            ],
        ),
    ]
