# Generated by Django 5.1.2 on 2024-11-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0003_alter_paciente_altura_alter_paciente_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cirugia_realizada',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='diagnostico_clinico_prequirurgico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nota_enfermeria',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='peso',
        ),
    ]
