# Generated by Django 5.1.2 on 2024-11-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0005_alter_paciente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cirugia_realizada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico_clinico_prequirurgico',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nota_enfermeria',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
