# Generated by Django 5.1.2 on 2024-11-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0009_alter_paciente_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='Hospital_Infantil.paciente'),
        ),
    ]
