# Generated by Django 5.1.2 on 2024-11-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0012_remove_tratamiento_otras_indicaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='otras_Indicaciones',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='otras_Indicaciones',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
