# Generated by Django 5.1.2 on 2024-11-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0014_alter_paciente_medico_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medico_Encargado',
            field=models.ForeignKey(limit_choices_to={'user__userprofile__funcionalidad': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital_Infantil.userprofile'),
        ),
    ]
