# Generated by Django 5.1.2 on 2024-11-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0015_alter_paciente_medico_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='expediente',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='id_Tratamiento',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
