# Generated by Django 5.1.2 on 2024-11-12 22:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0016_alter_paciente_expediente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id_Estudio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_Estudio', models.CharField(max_length=20)),
                ('fecha_realizada', models.DateField(default=django.utils.timezone.now)),
                ('estudio', models.FileField(upload_to='estudios/')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='Hospital_Infantil.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Radiografias',
            fields=[
                ('id_Radiografia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_Radiografia', models.CharField(max_length=20)),
                ('fecha_realizada', models.DateField(default=django.utils.timezone.now)),
                ('radiografia', models.FileField(upload_to='radiografias/')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiografias', to='Hospital_Infantil.paciente')),
            ],
        ),
    ]
