# Generated by Django 5.1.2 on 2024-12-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0017_estudios_radiografias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='historial_aplicacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='tratamiento_activo',
            field=models.CharField(choices=[('activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
