# Generated by Django 5.1.2 on 2024-12-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0019_alter_tratamiento_historial_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='historial_aplicacion',
            field=models.DateTimeField(null=True),
        ),
    ]
