# Generated by Django 5.1.2 on 2024-12-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0020_alter_tratamiento_historial_aplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='paciente_Habilitado',
            field=models.CharField(choices=[('Habilitado', 'Habilitado'), ('Deshabilitado', 'Deshabilitado')], default='Habilitado', max_length=15),
        ),
    ]
