# Generated by Django 5.1.2 on 2025-03-23 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0021_paciente_paciente_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='historial_aplicacion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermeros_Encargados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user__userprofile__funcionalidad': 'enfermero'}, related_name='pacientes_asignados', to='Hospital_Infantil.userprofile'),
        ),
        migrations.CreateModel(
            name='HistorialAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='Hospital_Infantil.tratamiento')),
            ],
        ),
    ]
