# Generated by Django 5.1.2 on 2025-02-24 02:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Infantil', '0021_paciente_paciente_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='Hospital_Infantil.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_SignoVital', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('temperatura', models.FloatField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('presion_arterial', models.CharField(max_length=20)),
                ('saturacion_oxigeno', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='Hospital_Infantil.paciente')),
            ],
        ),
    ]
