# Generated by Django 5.1.2 on 2025-03-26 02:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('expediente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('cirugia_realizada', models.CharField(max_length=100)),
                ('peso', models.FloatField(default=0.0)),
                ('altura', models.FloatField(default=0.0)),
                ('diagnostico_clinico_prequirurgico', models.CharField(max_length=1000)),
                ('nota_enfermeria', models.CharField(max_length=1000)),
                ('paciente_Habilitado', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Deshabilitado', 'Deshabilitado')], default='Habilitado', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id_Estudio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_Estudio', models.CharField(max_length=20)),
                ('fecha_realizada', models.DateField(default=django.utils.timezone.now)),
                ('estudio', models.FileField(upload_to='estudios/')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='server.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Radiografias',
            fields=[
                ('id_Radiografia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_Radiografia', models.CharField(max_length=20)),
                ('fecha_realizada', models.DateField(default=django.utils.timezone.now)),
                ('radiografia', models.FileField(upload_to='radiografias/')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiografias', to='server.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_Tratamiento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_Medicamento', models.CharField(max_length=50)),
                ('dosis_Administrada', models.FloatField()),
                ('via_Administracion', models.CharField(choices=[('cutanea', 'CUTANEA'), ('inhalada', 'INHALADA'), ('intradermica', 'INTRADERMICA'), ('im_intramuscular', 'IM-INTRAMUSCULAR'), ('iv_intravenosa', 'IV-INTRAVENOSA'), ('nasal', 'NASAL'), ('oftalmica', 'OFTALMICA'), ('oral', 'ORAL'), ('otica', 'OTICA'), ('rectal', 'RECTAL'), ('sonda_nasogastrica', 'SONDA NASOGASTRICA'), ('subcutanea', 'SUBCUTANEA'), ('sublingual', 'SUBLINGUAL'), ('topica', 'TOPICA'), ('vaginal', 'VAGINAL')], max_length=20)),
                ('frecuencia_Dosis', models.DecimalField(decimal_places=0, max_digits=2)),
                ('tiempo_Dosis', models.CharField(choices=[('hrs', 'HRS'), ('mins', 'MINS'), ('unica', 'UNICA'), ('prn', 'PRN')], max_length=10)),
                ('duracion_Terapia', models.DecimalField(decimal_places=0, max_digits=2)),
                ('otras_Indicaciones', models.CharField(max_length=1000, null=True)),
                ('tratamiento_activo', models.CharField(choices=[('activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='server.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='server.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('cedula_profesional', models.DecimalField(blank=True, decimal_places=0, max_digits=8)),
                ('funcionalidad', models.CharField(choices=[('administrador', 'ADMINISTRADOR'), ('medico', 'MEDICO'), ('enfermero', 'ENFERMERO')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermeros_Encargados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user__userprofile__funcionalidad': 'enfermero'}, related_name='pacientes_asignados', to='server.userprofile'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico_Encargado',
            field=models.ForeignKey(limit_choices_to={'user__userprofile__funcionalidad': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.userprofile'),
        ),
    ]
